import React, { useState, useCallback, useEffect } from "react";
import { 
  Sparkles, 
  Waves, 
  Orbit, 
  Cpu,
  X, 
  Maximize2, 
  Minimize2, 
  Volume2, 
  VolumeX, 
  RotateCcw,
  BookOpen,
  Sliders,
  Activity,
  Layers,
  HelpCircle,
  Camera,
  ChevronRight,
  Loader2
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { SimulationCanvas } from "../SimulationCanvas";
import { FluidLiquidCanvas2D } from "./FluidLiquidCanvas2D";
import DigitalLogicDesignLab from "../DigitalLogicDesignLab";
import { SIMULATION_PRESETS } from "../../lib/simulationPresets";
import { SimulationPreset } from "../../lib/simulationTypes";
import { generateSimulationWithGemini } from "../../services/simulationService";

export interface UniversalSimulationStudioProps {
  isOpen: boolean;
  onClose: () => void;
  onAskMahr?: (question: string) => void;
  onAskMyraa?: (question: string) => void;
  initialMode?: "2d-liquid" | "3d-webgl" | "dld-logic";
  initialPrompt?: string;
}

export const UniversalSimulationStudio: React.FC<UniversalSimulationStudioProps> = ({
  isOpen,
  onClose,
  onAskMahr,
  onAskMyraa,
  initialMode = "3d-webgl",
  initialPrompt = "3D Projectile Motion Laboratory & Vector Field"
}) => {
  const askHandler = onAskMahr || onAskMyraa;
  const [activeEngineMode, setActiveEngineMode] = useState<"2d-liquid" | "3d-webgl" | "dld-logic">(initialMode);
  const [promptInput, setPromptInput] = useState<string>("");
  const [isAiGenerating, setIsAiGenerating] = useState<boolean>(false);
  const [activePreset, setActivePreset] = useState<SimulationPreset>(SIMULATION_PRESETS[0]);
  const [notificationToast, setNotificationToast] = useState<string | null>(null);

  // Sync mode with initialMode prop when modal opens
  useEffect(() => {
    if (isOpen) {
      setActiveEngineMode(initialMode);
    }
  }, [isOpen, initialMode]);

  // Handle AI Prompt Simulation Generation
  const handleGenerateAISimulation = async (promptText: string) => {
    if (!promptText.trim() || isAiGenerating) return;

    const lower = promptText.toLowerCase();

    // Auto-detect if user wants Digital Logic Design (DLD) circuit
    if (
      lower.includes("logic") || 
      lower.includes("gate") || 
      lower.includes("adder") || 
      lower.includes("flip flop") || 
      lower.includes("flipflop") || 
      lower.includes("latch") || 
      lower.includes("multiplexer") || 
      lower.includes("mux") || 
      lower.includes("counter") || 
      lower.includes("subtractor") || 
      lower.includes("dld") || 
      lower.includes("boolean") || 
      lower.includes("truth table") || 
      lower.includes("nand") || 
      lower.includes("nor") || 
      lower.includes("xnor") || 
      lower.includes("xor") || 
      lower.includes("register")
    ) {
      setActiveEngineMode("dld-logic");
      setPromptInput("");
      return;
    }

    // Auto-detect if user wants liquid/fluid simulation
    if (
      lower.includes("liquid") || 
      lower.includes("fluid") || 
      lower.includes("water") || 
      lower.includes("vortex") || 
      lower.includes("swirl") || 
      lower.includes("viscous") || 
      lower.includes("navier") ||
      lower.includes("plume")
    ) {
      setActiveEngineMode("2d-liquid");
    }

    setIsAiGenerating(true);
    try {
      const matched = SIMULATION_PRESETS.find(p =>
        lower.includes(p.name.toLowerCase()) ||
        lower.includes(p.id.replace(/_/g, " "))
      );

      if (matched) {
        setActivePreset(matched);
        setNotificationToast(`Loaded preset: ${matched.name}`);
        setTimeout(() => setNotificationToast(null), 3000);
      } else {
        const result = await generateSimulationWithGemini(promptText);
        if (result.status === "success") {
          setNotificationToast("✨ AI Simulation Generated by Gemini!");
          setTimeout(() => setNotificationToast(null), 3500);
        }
      }
    } catch (e) {
      console.error("AI simulation generation failed:", e);
    } finally {
      setIsAiGenerating(false);
      setPromptInput("");
    }
  };

  if (!isOpen) return null;

  return (
    <div 
      id="universal-simulation-studio-modal"
      className="fixed inset-0 z-50 bg-[#020617]/95 backdrop-blur-2xl text-slate-100 flex flex-col overflow-hidden animate-in fade-in duration-200"
    >
      {/* Universal Engine Master Header Bar */}
      <header className="flex items-center justify-between px-4 py-2.5 bg-slate-950/90 border-b border-white/10 z-30 shrink-0">
        <div className="flex items-center gap-3">
          {/* Engine Logo & Title */}
          <div className="flex items-center gap-2">
            <div className={`w-8 h-8 rounded-xl flex items-center justify-center shadow-lg transition-all ${
              activeEngineMode === "2d-liquid"
                ? "bg-gradient-to-tr from-cyan-500 to-blue-600 shadow-cyan-500/25"
                : activeEngineMode === "dld-logic"
                ? "bg-gradient-to-tr from-emerald-500 to-teal-600 shadow-emerald-500/25"
                : "bg-gradient-to-tr from-purple-500 to-indigo-600 shadow-purple-500/25"
            }`}>
              {activeEngineMode === "2d-liquid" ? (
                <Waves className="w-4 h-4 text-slate-950 animate-pulse" />
              ) : activeEngineMode === "dld-logic" ? (
                <Cpu className="w-4 h-4 text-slate-950 animate-pulse" />
              ) : (
                <Orbit className="w-4 h-4 text-slate-950 animate-spin" />
              )}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-sm font-bold text-white font-mono tracking-tight">
                  Universal AI Simulation Engine
                </h1>
                <span className="px-1.5 py-0.2 rounded bg-cyan-500/20 text-cyan-300 text-[10px] font-mono border border-cyan-500/30">
                  v3.5 Unified
                </span>
              </div>
              <p className="text-[11px] text-slate-400 hidden sm:block">
                Unified 2D Liquid State, 3D WebGL Multi-Physics & Digital Logic Design Lab
              </p>
            </div>
          </div>

          {/* Unified Mode Switcher Pill */}
          <div className="flex items-center p-1 bg-slate-900 rounded-xl border border-white/10 ml-2">
            <button
              type="button"
              onClick={() => setActiveEngineMode("2d-liquid")}
              className={`px-3 py-1 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                activeEngineMode === "2d-liquid"
                  ? "bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 shadow-md"
                  : "text-slate-400 hover:text-white"
              }`}
              title="2D Navier-Stokes Fluid & Liquid Dynamics Simulation"
            >
              <Waves className="w-3.5 h-3.5" />
              <span>2D Liquid State</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveEngineMode("3d-webgl")}
              className={`px-3 py-1 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                activeEngineMode === "3d-webgl"
                  ? "bg-gradient-to-r from-purple-500 to-indigo-600 text-white shadow-md"
                  : "text-slate-400 hover:text-white"
              }`}
              title="3D WebGL Physics, Mechanics, Optics, Quantum & Astronomy Simulation"
            >
              <Orbit className="w-3.5 h-3.5" />
              <span>3D WebGL Space</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveEngineMode("dld-logic")}
              className={`px-3 py-1 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                activeEngineMode === "dld-logic"
                  ? "bg-gradient-to-r from-emerald-500 to-teal-500 text-slate-950 shadow-md"
                  : "text-slate-400 hover:text-white"
              }`}
              title="Digital Logic Design (DLD) & Microelectronic Circuit Synthesis"
            >
              <Cpu className="w-3.5 h-3.5" />
              <span>Digital Logic Lab</span>
            </button>
          </div>
        </div>

        {/* Right Actions */}
        <div className="flex items-center gap-2">
          {askHandler && (
            <button
              type="button"
              onClick={() => {
                const question = activeEngineMode === "2d-liquid"
                  ? "Can you explain the mathematical laws governing 2D Navier-Stokes fluid mechanics, viscosity, and vortex dynamics?"
                  : activeEngineMode === "dld-logic"
                  ? "Can you explain the Boolean algebra, circuit architecture, and gate propagation of this digital logic circuit?"
                  : `Can you explain the 3D physical principles behind ${activePreset.name}?`;
                askHandler(question);
              }}
              className="px-3 py-1.5 rounded-xl text-xs font-mono font-bold bg-purple-500/20 hover:bg-purple-500/30 border border-purple-500/40 text-purple-200 transition-all cursor-pointer hidden md:flex items-center gap-1.5"
              title="Ask MAHR Voice Companion about this simulation"
            >
              <Sparkles className="w-3.5 h-3.5 text-purple-400 animate-pulse" />
              <span>Ask MAHR</span>
            </button>
          )}

          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-900 hover:bg-rose-950/80 border border-white/10 hover:border-rose-500/40 text-slate-300 hover:text-rose-300 transition-all cursor-pointer shadow-md"
            title="Close Universal AI Simulation Studio"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </header>

      {/* Main Viewport Container */}
      <main className="relative flex-1 w-full h-full overflow-hidden">
        {activeEngineMode === "2d-liquid" ? (
          <FluidLiquidCanvas2D
            className="w-full h-full"
            onAskMahr={askHandler}
            onAskMyraa={askHandler}
            onToggle3DMode={() => setActiveEngineMode("3d-webgl")}
          />
        ) : activeEngineMode === "dld-logic" ? (
          <DigitalLogicDesignLab
            initialPrompt={promptInput || initialPrompt}
            onAskMahr={askHandler}
            onAskMyraa={askHandler}
            onClose={onClose}
            className="w-full h-full border-none rounded-none shadow-none"
          />
        ) : (
          <SimulationCanvas
            initialPrompt={initialPrompt}
            showOverlayControls={true}
            onAskMahr={askHandler}
            onAskMyraa={askHandler}
            onClose={onClose}
            className="w-full h-full border-none rounded-none shadow-none"
          />
        )}

        {/* Notification Toast */}
        {notificationToast && (
          <div className="absolute top-4 left-1/2 -translate-x-1/2 z-40 px-4 py-2 rounded-2xl bg-slate-950/90 border border-cyan-400/40 text-cyan-200 text-xs font-mono shadow-2xl flex items-center gap-2 animate-in fade-in slide-in-from-top-2">
            <span>{notificationToast}</span>
          </div>
        )}

        {/* Global Loading Overlay */}
        {isAiGenerating && (
          <div className="absolute inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex flex-col items-center justify-center gap-3">
            <Loader2 className="w-10 h-10 text-cyan-400 animate-spin" />
            <div className="text-center font-mono">
              <p className="text-sm font-bold text-white">Synthesizing Physical Formulation with Gemini</p>
              <p className="text-xs text-slate-400 mt-1">Generating vectors, boundary conditions, and differential equations...</p>
            </div>
          </div>
        )}
      </main>

      {/* Universal Floating AI Command Prompt Bar (Only in 2D mode where 3D has its own internal prompt bar) */}
      {activeEngineMode === "2d-liquid" && (
        <footer className="absolute bottom-4 left-1/2 -translate-x-1/2 z-30 w-full max-w-2xl px-4 pointer-events-auto">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleGenerateAISimulation(promptInput);
            }}
            className="bg-slate-950/90 backdrop-blur-2xl p-2 rounded-2xl border border-white/10 shadow-2xl flex items-center gap-2 focus-within:border-cyan-400/60 transition-all"
          >
            <div className="pl-2 text-cyan-400">
              <Sparkles className="w-4 h-4 animate-pulse" />
            </div>

            <input
              type="text"
              value={promptInput}
              onChange={(e) => setPromptInput(e.target.value)}
              placeholder="Prompt AI (e.g. 'Turbulent smoke vortex street', 'Viscous liquid honey flow', 'Surface wave ripple tank')..."
              className="flex-1 bg-transparent text-xs sm:text-sm text-slate-100 placeholder-slate-500 focus:outline-none px-2 py-1 font-mono"
              disabled={isAiGenerating}
            />

            <button
              type="submit"
              disabled={isAiGenerating || !promptInput.trim()}
              className="px-3 py-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 disabled:opacity-40 text-slate-950 font-bold text-xs font-mono flex items-center gap-1.5 transition-all shadow-lg cursor-pointer"
            >
              <span>Simulate</span>
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </form>
        </footer>
      )}
    </div>
  );
};
